In [132]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

knn = KNeighborsClassifier(n_neighbors = 1)

iris_data = pd.read_csv('iris.data', names=["sepalLengthCM", "sepalWidthCM", "petalLengthCM", "petalWidthCm","species"])

iris_data['species'] = (iris_data['species'] == 'Iris-setosa').astype(int)


train, test = np.split(iris_data.sample(frac=1), [int(0.75*len(iris_data))])

train

# #train the model
# knn.fit(X_train, y_train)

# #predict
# y_predict = knn.predict(X_test)

# print(classification_report(y_test, y_predict))
# y_predict

     sepalLengthCM  sepalWidthCM  petalLengthCM  petalWidthCm  species
79             5.7           2.6            3.5           1.0        0
77             6.7           3.0            5.0           1.7        0
95             5.7           3.0            4.2           1.2        0
144            6.7           3.3            5.7           2.5        0
123            6.3           2.7            4.9           1.8        0
..             ...           ...            ...           ...      ...
106            4.9           2.5            4.5           1.7        0
3              4.6           3.1            1.5           0.2        1
92             5.8           2.6            4.0           1.2        0
136            6.3           3.4            5.6           2.4        0
55             5.7           2.8            4.5           1.3        0

[112 rows x 5 columns]